name: Hello World
on: workflow_dispatch
jobs: 
 build:
   runs-on: ubuntu-latest
   steps:
     - name: build step
       run: echo "Bulding an application"

 test:
   runs-on: ubuntu-latest
   steps:
     - name: test app
       run: echo "Testing dependencies"

 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: deploy app
       run: echo "Deployment of application"
