name: Github Action
on: push
jobs: 
 Action_demo:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout the code
       uses: action/checkout@v4
     - name: Printing Index.html
       run: cat index.html

 
