name: Input demo
on:
   workflow_dispatch:
     inputs:
       environment:
         description: Choose environment variable
         required: true
         default: dev
         options:
           - dev
           - test
           - prod 
           
    artifact_tag:
          description: Choose the git tag
          required: true
jobs:
  input_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Depploying the ${{inputs.artifact_tag}} app to ${{inputs.environment}}"
       
    
